# TCL File Generated by Component Editor 13.0sp1
# Sun Apr 19 21:49:32 BST 2015
# DO NOT MODIFY


# 
# scdaq "Single-Channel Data Acquisition Unit" v1.0
# Petros Fountas 2015.04.19.21:49:32
# AnalogDigital single-channel data acquisition unit with configurable trigger.
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module scdaq
# 
set_module_property DESCRIPTION "AnalogDigital single-channel data acquisition unit with configurable trigger."
set_module_property NAME scdaq
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP DSP
set_module_property AUTHOR "Petros Fountas"
set_module_property DISPLAY_NAME "Single-Channel Data Acquisition Unit"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL scdaq
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file scdaq.v VERILOG PATH hdl/scdaq.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter NSAMPLES INTEGER 256
set_parameter_property NSAMPLES DEFAULT_VALUE 256
set_parameter_property NSAMPLES DISPLAY_NAME NSAMPLES
set_parameter_property NSAMPLES TYPE INTEGER
set_parameter_property NSAMPLES UNITS None
set_parameter_property NSAMPLES ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NSAMPLES HDL_PARAMETER true
add_parameter PRECISION INTEGER 14
set_parameter_property PRECISION DEFAULT_VALUE 14
set_parameter_property PRECISION DISPLAY_NAME PRECISION
set_parameter_property PRECISION TYPE INTEGER
set_parameter_property PRECISION UNITS None
set_parameter_property PRECISION ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PRECISION HDL_PARAMETER true
add_parameter NCTPSAMPLES INTEGER 8
set_parameter_property NCTPSAMPLES DEFAULT_VALUE 8
set_parameter_property NCTPSAMPLES DISPLAY_NAME NCTPSAMPLES
set_parameter_property NCTPSAMPLES TYPE INTEGER
set_parameter_property NCTPSAMPLES UNITS None
set_parameter_property NCTPSAMPLES ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NCTPSAMPLES HDL_PARAMETER true
add_parameter RDO_ADD_BLEN INTEGER 8
set_parameter_property RDO_ADD_BLEN DEFAULT_VALUE 8
set_parameter_property RDO_ADD_BLEN DISPLAY_NAME RDO_ADD_BLEN
set_parameter_property RDO_ADD_BLEN TYPE INTEGER
set_parameter_property RDO_ADD_BLEN UNITS None
set_parameter_property RDO_ADD_BLEN ALLOWED_RANGES -2147483648:2147483647
set_parameter_property RDO_ADD_BLEN HDL_PARAMETER true
add_parameter CFG_ADD_BLEN INTEGER 5
set_parameter_property CFG_ADD_BLEN DEFAULT_VALUE 5
set_parameter_property CFG_ADD_BLEN DISPLAY_NAME CFG_ADD_BLEN
set_parameter_property CFG_ADD_BLEN TYPE INTEGER
set_parameter_property CFG_ADD_BLEN UNITS None
set_parameter_property CFG_ADD_BLEN ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CFG_ADD_BLEN HDL_PARAMETER true


# 
# display items
# 


# 
# connection point cfg
# 
add_interface cfg avalon end
set_interface_property cfg addressUnits WORDS
set_interface_property cfg associatedClock clk
set_interface_property cfg associatedReset reset
set_interface_property cfg bitsPerSymbol 8
set_interface_property cfg burstOnBurstBoundariesOnly false
set_interface_property cfg burstcountUnits WORDS
set_interface_property cfg explicitAddressSpan 0
set_interface_property cfg holdTime 0
set_interface_property cfg isMemoryDevice true
set_interface_property cfg linewrapBursts false
set_interface_property cfg maximumPendingReadTransactions 10
set_interface_property cfg readLatency 0
set_interface_property cfg readWaitTime 1
set_interface_property cfg setupTime 0
set_interface_property cfg timingUnits Cycles
set_interface_property cfg writeWaitTime 0
set_interface_property cfg ENABLED true
set_interface_property cfg EXPORT_OF ""
set_interface_property cfg PORT_NAME_MAP ""
set_interface_property cfg SVD_ADDRESS_GROUP ""

add_interface_port cfg avs_cfg_address address Input "(CFG_ADD_BLEN) - (0) + 1"
add_interface_port cfg avs_cfg_read read Input 1
add_interface_port cfg avs_cfg_write write Input 1
add_interface_port cfg avs_cfg_waitrequest waitrequest Output 1
add_interface_port cfg avs_cfg_readdatavalid readdatavalid Output 1
add_interface_port cfg avs_cfg_readdata readdata Output 16
add_interface_port cfg avs_cfg_writedata writedata Input 16
add_interface_port cfg avs_cfg_response response Output 2
set_interface_assignment cfg embeddedsw.configuration.isFlash 0
set_interface_assignment cfg embeddedsw.configuration.isMemoryDevice 1
set_interface_assignment cfg embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment cfg embeddedsw.configuration.isPrintableDevice 0


# 
# connection point rdo
# 
add_interface rdo avalon end
set_interface_property rdo addressUnits WORDS
set_interface_property rdo associatedClock clk
set_interface_property rdo associatedReset reset
set_interface_property rdo bitsPerSymbol 8
set_interface_property rdo burstOnBurstBoundariesOnly false
set_interface_property rdo burstcountUnits WORDS
set_interface_property rdo explicitAddressSpan 0
set_interface_property rdo holdTime 0
set_interface_property rdo isMemoryDevice true
set_interface_property rdo linewrapBursts false
set_interface_property rdo maximumPendingReadTransactions 10
set_interface_property rdo readLatency 0
set_interface_property rdo readWaitTime 1
set_interface_property rdo setupTime 0
set_interface_property rdo timingUnits Cycles
set_interface_property rdo writeWaitTime 0
set_interface_property rdo ENABLED true
set_interface_property rdo EXPORT_OF ""
set_interface_property rdo PORT_NAME_MAP ""
set_interface_property rdo SVD_ADDRESS_GROUP ""

add_interface_port rdo avs_rdo_address address Input "(RDO_ADD_BLEN) - (0) + 1"
add_interface_port rdo avs_rdo_read read Input 1
add_interface_port rdo avs_rdo_write write Input 1
add_interface_port rdo avs_rdo_waitrequest waitrequest Output 1
add_interface_port rdo avs_rdo_readdatavalid readdatavalid Output 1
add_interface_port rdo avs_rdo_readdata readdata Output 16
add_interface_port rdo avs_rdo_response response Output 2
add_interface_port rdo avs_rdo_writedata writedata Input 16
set_interface_assignment rdo embeddedsw.configuration.isFlash 0
set_interface_assignment rdo embeddedsw.configuration.isMemoryDevice 1
set_interface_assignment rdo embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment rdo embeddedsw.configuration.isPrintableDevice 0


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint rdo
set_interface_property interrupt_sender associatedClock clk
set_interface_property interrupt_sender associatedReset reset
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender ins_irq irq Output 1


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk csi_clock clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_reset_n reset_n Input 1

